/*
 * Name:
 * Assignment: Random Number Generator and Analysis Tool
 */
public class RandomInts {
    public static void main(String[] args) {
        
    }

    /**
     * This method generates a random integer (from low to high) using Math.random()
     * 
     * @param low The lowest value intended to be output by randomInt
     * @param high The highest value intended to be output by randomInt
     * @return a random number between low and high (inclusive)
     */
    public static int randomInt(int low, int high) {
        // TODO: 
        return -1;
    }

    /**
     * This method will print statistics about the random numbers generated by randomInt
     * 
     * If randomInt outputs a value outside of the desired range, it should just print a 
     * message saying that the randomInt generator isn't working properly
     * 
     * Otherwise, it should count how many times each value came up and print those stats
     * It should also print the average of all of the values generated.
     * 
     * @param low The lowest value intended to be output by randomInt
     * @param high The highest value intended to be output by randomInt
     * @param numSamples The number of times this analyzer will call randomInt
     */
    public static void randomIntAnalyzer( int low, int high, int numSamples) {
        // TODO: 
    }
}
